In [16]:
%load_ext autoreload
%autoreload 2
import sys, os
import numpy as np

sys.path.append('src')
# sys.path = ['src']
from basic.lib.simm import Sim

sim = Sim({'cache_dir': '/export/data/billi/tmp/tmp_simlf/cache/cn'})
sys.path = ['/home/billi/entrance/analytool/dao/bag/simlf',  '/home/billi/miniconda3/envs/billi/lib/python39.zip', '/home/billi/miniconda3/envs/billi/lib/python3.9', '/home/billi/miniconda3/envs/billi/lib/python3.9/lib-dynload', '/home/billi/miniconda3/envs/billi/lib/python3.9/site-packages', 'src']


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [17]:
sim_ = Sim({'cache_dir': '/export/data/billi/tmp/yang/cache/cn/'})

In [18]:
x = sim.load_mod('sup_taq/i_trd_dvol')
y = sim_.load_mod('sup_taq/i_trd_dvol')


(2877, 50, 6000)

In [27]:
mask = np.abs(x[:y.shape[0]] - y) > 0.1
np.where(mask)

(array([   0,    0,    1, ..., 2454, 2454, 2454]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([3671, 3683, 3671, ..., 4771, 4883, 4886]))

In [32]:
x[3, 0:5, 3671], y[3, 0:5, 3671]

(memmap([2568006.,      nan,      nan,      nan,      nan], dtype=float32),
 memmap([ 0., nan, nan, nan, nan], dtype=float32))

In [35]:
x[0,:,0], y[0,:,0]

(memmap([1211760., 5418456.,  575262.,  789930.,  118054.,  122610.,
          123950.,  445148.,  196578.,   97016.,  169644.,  130382.,
          169778.,  486018.,  189610.,   27738.,   25862.,  111354.,
          306056.,   48106.,   34974.,   77452.,   17956.,   86832.,
          115240.,      nan,  424378.,  104654.,   61104.,   32562.,
           74772.,    8576.,   55610.,   66464.,   24120.,   37386.,
           29480.,  100232.,   19296.,   70886.,  152760.,  127702.,
           73030.,  296542.,   13534.,   23584.,   35912.,  122342.,
          226996.,  276442.], dtype=float32),
 memmap([1211760., 5418456.,  575262.,  789930.,  118054.,  122610.,
          123950.,  445148.,  196578.,   97016.,  169644.,  130382.,
          169778.,  486018.,  189610.,   27738.,   25862.,  111354.,
          306056.,   48106.,   34974.,   77452.,   17956.,   86832.,
          115240.,      nan,  424378.,  104654.,   61104.,   32562.,
           74772.,    8576.,   55610.,   66464.,   24120.

In [38]:
x = sim.load_mod('sup_taq/i_trd_last')
y = sim_.load_mod('sup_taq/i_trd_last')
x, y

(memmap([[[1.35, 5.1 ,  nan, ...,  nan,  nan,  nan],
          [1.34, 5.11,  nan, ...,  nan,  nan,  nan],
          [1.34, 5.14,  nan, ...,  nan,  nan,  nan],
          ...,
          [1.34, 5.07,  nan, ...,  nan,  nan,  nan],
          [1.34, 5.06,  nan, ...,  nan,  nan,  nan],
          [1.34, 5.05,  nan, ...,  nan,  nan,  nan]],
 
         [[1.3 , 5.02,  nan, ...,  nan,  nan,  nan],
          [1.28, 5.07,  nan, ...,  nan,  nan,  nan],
          [1.27, 5.11,  nan, ...,  nan,  nan,  nan],
          ...,
          [1.33, 5.13,  nan, ...,  nan,  nan,  nan],
          [1.32, 5.13,  nan, ...,  nan,  nan,  nan],
          [1.33, 5.12,  nan, ...,  nan,  nan,  nan]],
 
         [[1.32, 5.14,  nan, ...,  nan,  nan,  nan],
          [1.32, 5.13,  nan, ...,  nan,  nan,  nan],
          [1.32, 5.1 ,  nan, ...,  nan,  nan,  nan],
          ...,
          [1.31, 5.11,  nan, ...,  nan,  nan,  nan],
          [1.32, 5.1 ,  nan, ...,  nan,  nan,  nan],
          [1.32, 5.1 ,  nan, ...,  nan,  nan,  n

In [39]:
mask = np.abs(x[:y.shape[0]] - y) > 0.1
np.where(mask)

(array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))

In [ ]:
t = np.logical_xor(np.isfinite(x[:y.shape[0]]), np.isfinite(y))

array([[[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, Fal

In [ ]:
np.where(t)

(array([   0,    0,    0, ..., 2454, 2454, 2454]),
 array([ 0,  0,  1, ..., 49, 49, 49]),
 array([3671, 3683, 3671, ..., 4886, 4895, 4904]))

In [55]:
x[0,0:5, 3671], y[0,0:5, 3671]

(memmap([7., 7., 7., 7., 7.], dtype=float32),
 memmap([nan, nan, nan, nan, nan], dtype=float32))

In [57]:
sim.register_pnl3().pnl3.set_fields(region='cn')

sim.pnl3.show_pnls(x, start_date=20220101, freq='yearly', plot=False)

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed