In [1]:
%load_ext autoreload
%autoreload 2
import sys, os
import numpy as np

sys.path.append('src')
# sys.path = ['src']
from basic.lib.simm import Sim

sim = Sim({'cache_dir': 'tmp/cache/cn/'})
sys.path = ['/home/billi/entrance/analytool/dao/bag/simlf',  '/home/billi/miniconda3/envs/billi/lib/python39.zip', '/home/billi/miniconda3/envs/billi/lib/python3.9', '/home/billi/miniconda3/envs/billi/lib/python3.9/lib-dynload', '/home/billi/miniconda3/envs/billi/lib/python3.9/site-packages', 'src']


In [2]:
from scripts.prophet.train import run

In [13]:
workdir='tmp/cache/cn/model/lgbm/grp_lgbm_kdr/0'
config=('scripts/prophet/config/train_lgbm_addlimit.yml',)
inds=('src/user/kdr_py/inds_200.yml',)
data_dir = ""
sys_data_dir='tmp/cache/cn/sys'
user_data_dir='tmp/cache/cn/user'
resume=True
start_date=None
end_date=None
random_state=0
grf=False
univ=''


a = run(workdir=workdir,
        config=config,
        inds=inds,
        data_dir=data_dir,
        user_data_dir=user_data_dir,
        sys_data_dir=sys_data_dir,
        resume=resume,
        start_date=start_date,
        end_date=end_date,
        random_state=random_state,
        grf=grf,
        univ=univ,
)

ERROR:root:--begin load_xy
ERROR:root:--begin
ERROR:root:--path = tmp/cache/cn/sys/ext/fret_raw_1
ERROR:root:--Y.nansum = 4.412248611450195
ERROR:root:--Y shape, (6000, 2944, 1), univ_size: 5661, start_di :0, end_di:2672
ERROR:root:--Y.nansum 2 = 4.412248611450195
ERROR:root:--Y shape, (5661, 2672, 1)
ERROR:root:--Y.nansum 3 = 0.0


In [35]:
import matplotlib.pyplot as plt
sim = Sim({'cache_dir': 'tmp/cache/cn_jp/'})
x = sim.load_mod('test/kdr_py_1')

In [36]:
adj = sim.load_mod('base/adj')
close = sim.load_mod('base/close')
adj_close = sim.load_mod('base/adj_close')
univ_all = sim.load_mod('base/univ_all')

In [ ]:
adj_close[90:100, 0]


memmap([15.18    , 15.55    , 15.12    , 15.31    , 15.9     , 16.106178,
        15.718079, 15.281466, 15.354234, 14.941876], dtype=float32)

In [92]:
sim = Sim({'cache_dir': 'tmp/cache/cn/'})
sim2 = Sim({'cache_dir': '../../yang/tmp/cache/cn/'})
u = sim.load_mod('base/univ_all')[:2000]
u2 = sim2.load_mod('base/univ_all')[:2000]

In [96]:
a = sim.load_mod('sup_univ/cninfo')[:2000].copy()
b = sim2.load_mod('sup_univ/cninfo')[:2000].copy()
# a[~u] = np.nan
# b[~u2] = np.nan

In [100]:

a = sim.load_mod('sup_univ/st')[:2000].copy()
b = sim2.load_mod('sup_univ/st')[:2000].copy()
c = sim.load_mod('sup_univ/cninfo')[:2000].copy()
d = sim2.load_mod('sup_univ/cninfo')[:2000].copy()
e = sim.load_mod('sup_univ/cninfo1')[:2000].copy()
f = sim2.load_mod('sup_univ/cninfo1')[:2000].copy()

In [101]:
np.sum(a != b), np.sum(c != d), np.sum(e != f)

(0, 21, 112)

In [103]:
e_ = c.copy()
e_[a] =False
f_ = d.copy()
f_[b] =False
np.sum(e_ != e), np.sum(f_ != f)

(0, 91)

In [105]:
x,y = 1909, 3759
a[x, y], b[x, y], c[x, y], d[x, y], e[x, y], f[x, y]

(False, False, True, True, True, False)

In [104]:
np.where(f_ != f)

(array([1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919,
        1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930,
        1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941,
        1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952,
        1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963,
        1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974,
        1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985,
        1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996,
        1997, 1998, 1999]),
 array([3759, 3759, 3759, 3759, 3759, 3759, 3759, 3759, 3759, 3759, 3759,
        3759, 3759, 3759, 3759, 3759, 3759, 3759, 3759, 3759, 3759, 3759,
        3759, 3759, 3759, 3759, 3759, 3759, 3759, 3759, 3759, 3759, 3759,
        3759, 3759, 3759, 3759, 3759, 3759, 3759, 3759, 3759, 3759, 3759,
        3759, 3759, 3759, 3759, 3759, 3759, 3759, 3759, 3759, 3759, 3759,
        37

In [85]:
np.sum(np.isfinite(a)), np.sum(np.isfinite(b)), np.sum(np.isfinite(a)) - np.sum(np.isfinite(b))

(5971015, 5971013, 2)

In [90]:
np.sum(np.abs(a - b) > 1e-9)

0

In [88]:
a, b

(memmap([[        nan,         nan,         nan, ...,         nan,
                  nan,         nan],
         [-0.00746268,  0.0138613 ,         nan, ...,         nan,
                  nan,         nan],
         [-0.00751877, -0.00390625,         nan, ...,         nan,
                  nan,         nan],
         ...,
         [        nan,         nan,         nan, ...,         nan,
                  nan,         nan],
         [        nan,         nan,         nan, ...,         nan,
                  nan,         nan],
         [        nan,         nan,         nan, ...,         nan,
                  nan,         nan]], dtype=float32),
 memmap([[        nan,         nan,         nan, ...,         nan,
                  nan,         nan],
         [-0.00746268,  0.0138613 ,         nan, ...,         nan,
                  nan,         nan],
         [-0.00751877, -0.00390625,         nan, ...,         nan,
                  nan,         nan],
         ...,
         [        n

In [42]:
np.where(a != b)

(array([1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244, 1245,
        1246, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1464, 1699]),
 array([3412, 3412, 3412, 3412, 3412, 3412, 3412, 3412, 3412, 3412, 3412,
        3412, 3412, 3412, 3412, 3412, 3412, 3412, 3412, 3683, 3671]))

In [46]:
a[1230:1260, 3412], b[1230:1260, 3412]

(memmap([ True,  True,  True,  True,  True, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False]),
 memmap([ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True, False,
         False, False,  True,  True,  True,  True,  True,  True,  True,
         False, False, False]))